base_config: configs/replica/replica.yaml

exp_name: replica/room0/debug

data_specs:
  data_path: './Datasets/Replica/room0'
  max_depth: 10
  use_gt: True

decoder_specs:
  # [x_min,x_max],[y_min,y_max],[z_min,z_max]
  # nice-slam's bound + [10,10,10]
  # bound: [ [ 8.5,17.6 ],[ 8,14 ],[ 7.5,12 ] ]
    bound: [ [ 0,10 ],[ 0,6 ],[ 0,4 ] ]


