identifier: grad_sdf.gui_base.GuiBaseConfig

panel_split_ratio: 0.7

view_option: follow
view_file: room0_view0.yaml
objects: [scan, traj, current_cam, sdf_slice, octree]
# scan, traj, kf_cams, current_cam, octree, sdf_slice, sdf_slice_prior, sdf_slice_residual, mesh, mesh_prior, gt_mesh

scan_point_size: 1
scan_point_downsample: 4
scan_point_color: [0.8, 0.8, 1.0]

traj_line_width: 5
traj_color: [1.0, 0.0, 0.0]

camera_line_width: 8
camera_size: 0.25
camera_color_current: [0.0, 1.0, 0.0]
camera_color_key_frame: [0.0, 0.0, 1.0]
camera_color_selected_key_frame: [1.0, 0.5, 0.0]

octree_line_width: 2
octree_update_freq: 20
octree_min_size: 1
octree_color: [0.8, 0.8, 0.8]

mesh_update_freq: 10
mesh_resolution: 10
mesh_height_color_map: jet
mesh_color_option: normal

sdf_slice_update_freq: 10
sdf_slice_resolution: 50
sdf_point_size: 22
sdf_slice_axis: 2
sdf_slice_position: 1.1
sdf_color_map: jet

experiment_name: grad_sdf
scene_bound_min: [-10.0, -10.0, -10.0]
scene_bound_max: [10.0, 10.0, 10.0]
gt_mesh_path:
gt_mesh_offset:

mesh_remove_ceiling: true
mesh_ceiling_thickness: 0.6
