base_config: trainer.yaml
exp_name: replica_room_0
data:
    dataset_args:
        data_path: "/home/daizhirui/DataArchive/Replica-SDF-aug/room0"
        max_depth: 10.0
        use_gt: true
model:
    residual_net_cfg:
        bound: [[0, 10], [0, 6], [0, 4]]
