# Scene: room0,
# bound_min: [-3.8696494102478027, -2.347562551498413, -1.4041465520858765]
# bound_max: [3.869352102279663, 2.348031520843506, 1.3950726985931396]

base_config: trainer.yaml
exp_name: replica_room0
data:
    dataset_args:
        data_path: "/home/daizhirui/DataArchive/Replica-SDF-aug/room0"
#        data_path: '/home/daizhirui/DataArchive/Replica/room0'
        max_depth: 10.0
        # offset: [4.02, 4.02, 4.02]
        # bound_min: [2.47, 1.52, 0.0]
        # bound_max: [5.57, 6.52, 8.04]
        offset: [4.4, 3.0, 2.0]
        bound_min: [0.5, 0.5, 0.5]  # used to filter points out of bound after offset is applied
        bound_max: [8.5, 5.5, 3.5]
model:
    residual_net_cfg:
        # bound_min: [2.47, 1.52, 0.0]
        # bound_max: [5.57, 6.52, 8.04]
        bound_min: [0, 0, 0]
        bound_max: [9.0, 6.0, 4.0]