# Scene: office0
# bound_min: [-2.363569736480713, -1.9737036228179932, -1.4879510402679443]
# bound_max: [2.3736791610717773, 1.9777350425720215, 1.4847674369812012]

base_config: trainer.yaml
exp_name: replica_office0
data:
    dataset_args:
        data_path: "/home/daizhirui/DataArchive/Replica-SDF-aug/office0"
        max_depth: 10.0
        offset: [2.5, 2.5, 2.0]
        bound_min: [0.5, 0.5, 0.5]
        bound_max: [5.0, 4.5, 3.5]
model:
    residual_net_cfg:
        bound_min: [0.0, 0.0, 0.0]
        bound_max: [5.5, 5.0, 4.0]