intrinsics:
    - [720, 0, 960]
    - [0, 720, 540]
    - [0, 0, 1]
extrinsics:
    - [-0.07, 0.998, 0.0, -2.219]
    - [0.614, 0.043, -0.788, -2.508]
    - [-0.786, -0.055, -0.615, 7.772]
    - [0.0, 0.0, 0.0, 1.0]
fov: 90.0
