intrinsics:
    - [720, 0, 960]
    - [0, 720, 720]
    - [0, 0, 1]
extrinsics:
    - [-0.025, -1.0, 0.0, 3.089]
    - [-0.857, 0.021, -0.515, 2.998]
    - [0.515, -0.013, -0.857, 2.853]
    - [0.0, 0.0, 0.0, 1.0]
fov: 90.0
