intrinsics:
    - [720, 0, 896]
    - [0, 720, 720]
    - [0, 0, 1]
extrinsics:
    - [-0.067, 0.998, 0.0, -1.981]
    - [0.650, 0.043, -0.759, -2.995]
    - [-0.757, -0.051, -0.651, 7.860]
    - [0.0, 0.0, 0.0, 1.0]
fov: 90.0
